package interfaz;

import afn.AFN;
import infijaPosfija.InfijaAPosfija;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac
 */
public class Inicio extends javax.swing.JFrame {
    InfijaAPosfija expresion = new InfijaAPosfija();
    AFN afn;
    
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevaRegExp = new javax.swing.JToggleButton();
        BotonGeneraAFN = new javax.swing.JToggleButton();
        botonGeneraAFD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonNuevaRegExp.setText("Nueva Expresión Regular");
        botonNuevaRegExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaRegExpActionPerformed(evt);
            }
        });

        BotonGeneraAFN.setText("Generar AFN");
        BotonGeneraAFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGeneraAFNActionPerformed(evt);
            }
        });

        botonGeneraAFD.setText("Generar AFD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonNuevaRegExp, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(BotonGeneraAFN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGeneraAFD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(botonNuevaRegExp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonGeneraAFN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(botonGeneraAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


//INICIO, INTRODUCIR REGEXP Y CREAR NOTACION POSFIJA
    
    private void botonNuevaRegExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaRegExpActionPerformed
        
        String expresionEntrada = null;
        expresionEntrada = JOptionPane.showInputDialog("Por favor, introduzca la Expresion Regular");
        if (expresionEntrada != null) {
            expresion.setNotacionInfija(expresionEntrada);
            if(expresion.inicioInfijaAPosfija()){
                JOptionPane.showMessageDialog(this, "La espresion regular <<"+ expresion.getNotacionInfija() +">> en notacion posfija es: \n" + expresion.getNotacionPosfija());
            }else{
                JOptionPane.showMessageDialog(this, "Ocurrio un error al intentar generar la notacion posfija de la expresion regular");
            }
            
        }

    }//GEN-LAST:event_botonNuevaRegExpActionPerformed

    private void BotonGeneraAFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGeneraAFNActionPerformed
        afn = new AFN(expresion.getNotacionPosfija());
        afn.iniciarCreaAFN();
    }//GEN-LAST:event_BotonGeneraAFNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonGeneraAFN;
    private javax.swing.JButton botonGeneraAFD;
    private javax.swing.JToggleButton botonNuevaRegExp;
    // End of variables declaration//GEN-END:variables
}
